# Configure the PHP version SensioLabsInsight should use to analyze
# your project. It can be defined to 5, 7.0, or 7.1. If not
# present, it will prefer 7.1 but fallback to 5 if errored.
php_version: 7.1

# Configure which PHP extensions your project need to be analyzed.
php_ini: |
    extension=openssl.so
    extension=mcrypt.so

# Ignore some branches to avoid triggering analysis for these
#ignore_branches:
#    - gh-pages

# Configure the failure conditions for your commit status.
# If at least one of these conditions is verified, the commit status is displayed as failed.
commit_failure_conditions:
    # By severities count (default configuration, any change will override it)
    - "project.severity.critical > 0"
    - "project.severity.major > 0"

    # # By other severities count
    # - "project.severity.minor > 0"
    # - "project.severity.info >= 15"
    #
    # # By categories count
    # - "project.category.architecture > 0"
    # - "project.category.bugrisk > 0"
    # - "project.category.codestyle > 0"
    # - "project.category.deadcode > 0"
    # - "project.category.performance > 0"
    # - "project.category.readability > 0"
    # - "project.category.security > 0"
    #
    # # By project grade (none, bronze, silver, gold, platinum)
    # - "project.grade < gold"
    #
    # # By total violations count
    # - "project.violations > 150"
    #
    # By severities count, limited to the violations concerning files edited by the current PR
    # - "pr.severity.critical > 0"
    # - "pr.severity.major > 0"
    # - "pr.severity.minor > 0"
    # - "pr.severity.info >= 15"
    #
    # # By categories count, limited to the violations concerning files edited by the current PR
    # - "pr.category.architecture > 0"
    # - "pr.category.bugrisk > 0"
    # - "pr.category.codestyle > 0"
    # - "pr.category.deadcode > 0"
    # - "pr.category.performance > 0"
    # - "pr.category.readability > 0"
    # - "pr.category.security > 0"
    #
    # # By total violations count, limited to the violations concerning files edited by the current PR
    # - "pr.violations > 150"

# Configure rules.
rules:
    # Disable a rule
    php.class_too_long:
        enabled: true

    # Re-enable a rule that is disabled by default
    #symfony.use_dir_file_constant:
    #    enabled: true

    # Configure a rule
    php.class_too_long:
        max_length: 2000
        threshold:  10

# Configure in which directory your code is located.
# This can be set to any subdirectory of your project.
working_directory: .

# Configure the directories excluded from the analysis. By default,
# this setting excldues directories commonly used to store tests
# and third-party libraries.
global_exclude_dirs:
    - vendor
    - vendors
    - test
    - tests
    - Tests
    - spec
    - features
    - Fixtures
    - DataFixtures
    - var

# Configure patterns used by SensioLabsInsight to exclude specific
# files and directories.
exclude_patterns:
    - app/check.php
    - app/SymfonyRequirements.php
    - web/config.php
    - web/app_*.php
