upjv:
    resource: "@UpjvBundle/Controller/"
    type:   annotation

app:
    resource: '@AppBundle/Controller/'
    type: annotation


login:
    path: /connexion
    defaults: { _controller: UpjvBundle:Login:login }

login_check:
    path: /connexion

logout:
    path: /logout
