# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
      UpjvBundle\Entity\Utilisateur: sha512

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
          id: fos_user.user_provider.username_email

    role_hierarchy:
      ROLE_ETUDIANT: ROLE_USER
      ROLE_ADMIN: ROLE_ETUDIANT
      ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
          pattern: ^/
          anonymous: true
          form_login:
            provider: fos_userbundle
            login_path: fos_user_security_login
            check_path: fos_user_security_check
          logout: true

    access_control:
      - { path: ^/admin, roles: ROLE_SUPER_ADMIN }
      - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
