# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
          id: fos_user.user_provider.username_email

        users:
          entity:
            class: UpjvBundle:Utilisateur
            property: email

        in_memory:
          memory:
            users:
              dupont: { password: dupont, roles: ['ROLE_USER']}


    encoders:
      Symfony\Component\Security\Core\User\User: plaintext
      UpjvBundle\Entity\Utilisateur: plaintext

    role_hierarchy:
      ROLE_ADMIN: ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
          pattern: ^/
          anonymous: true
          provider: main
          form_login:
            login_path: connexion
            check_path: connexion
          logout:
            path: /logout
            target: /connexion

    access_control:
      - { path: ^/admin, roles: ROLE_ADMIN }
