<?php

namespace UpjvBundle\Repository;

/**
 * GroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByMatiere ($arrayMatiere) {
        $queryBuilder = $this->createQueryBuilder('e');
        $queryBuilder
            ->where('e.matiere IN (:matiere)')
            ->setParameter('matiere', $arrayMatiere);

        return $queryBuilder->getQuery()->getResult();
    }

}
