<?php

namespace UpjvBundle\Repository;

/**
 * GroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatiereProfesseurRepository extends \Doctrine\ORM\EntityRepository
{
}
