<?php

namespace UpjvBundle\Repository;
use UpjvBundle\Entity\Parcours;

/**
 * MatiereParcoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatiereParcoursRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param $parcours Parcours
     * @return mixed
     */
    public function findOptionelleByParcours ($parcours) {
        $queryBuilder = $this->createQueryBuilder('e');
        $queryBuilder
            ->where('e.parcours = :parcours')
            ->andWhere('e.optionnel = true')
            ->setParameter('parcours', $parcours);

        return $queryBuilder->getQuery()->getResult();
    }

    public function findMatieresByParcours ($arrayParcours) {
        $queryBuilder = $this->createQueryBuilder('e');
        $queryBuilder
            ->where("e.parcours IN (:parcours)")
            ->setParameter("parcours", $arrayParcours);

        return $queryBuilder->getQuery()->getResult();
    }

}
