<?php

namespace UpjvBundle\Repository;
use UpjvBundle\Entity\Matiere;

/**
 * MatiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatiereRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return mixed
     * Order all Matiere by Code
     */
    public function findAll(){
        return $this->createQueryBuilder('m')->orderBy('m.code','ASC');
    }

    /**
     * @return mixed
     * Order all Matiere by Code
     */
    public function findAllToArray(){
        $queryBuilder = $this->createQueryBuilder('m');

        /** @var Matiere $result */
        foreach ($queryBuilder->getQuery()->getResult() as $result){
            $tabResult[$result->getCode()] = $result;
        }
        ksort($tabResult);
        return $tabResult;
    }

    public function resetMatiereUtilisateur(){
        $rawSql = "DELETE FROM utilisateur_matiere";

        $stmt = $this->getEntityManager()->getConnection()->prepare($rawSql);
        $stmt->execute();
    }
}
