<?php

namespace UpjvBundle\Repository;
use UpjvBundle\Entity\Matiere;
use UpjvBundle\Entity\PoleDeCompetence;

/**
 * MatiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatiereRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return mixed
     * Order all Matiere by Code
     */
    public function findAll(){
        return $this->createQueryBuilder('m')->orderBy('m.code','ASC');
    }

    /**
     * @return mixed
     * Order all Matiere by Code
     */
    public function findAllToArray(){
        $queryBuilder = $this->createQueryBuilder('m')->orderBy('m.code','ASC');
        return $queryBuilder->getQuery()->getResult();
    }

    public function resetMatiereUtilisateur(){
        $rawSql = "DELETE FROM utilisateur_matiere";

        $stmt = $this->getEntityManager()->getConnection()->prepare($rawSql);
        $stmt->execute();
    }

    public function findDistinctMatiereByPoleAndOrdre($ordre, PoleDeCompetence $poleDeCompetence, $optionnel = false){
        return $this
            ->createQueryBuilder('m')
            ->join('m.optionnel','optionnel')
            ->where('m.poleDeCompetence = :poleDeCompetence')
            ->setParameter('poleDeCompetence', $poleDeCompetence)
            ->andWhere('optionnel.ordre = :ordre')
            ->setParameter('ordre',$ordre)
            ->distinct()
            ->getQuery()
            ->getResult()
            ;
    }
}
