<?php

namespace UpjvBundle\Repository;

/**
 * OptionnelleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionnelleRepository extends \Doctrine\ORM\EntityRepository
{
}
