<?php

namespace UpjvBundle\Repository;
use UpjvBundle\Entity\Semestre;

/**
 * ParcoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParcoursRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBySemestre(Semestre $semestre){
        return $this->createQueryBuilder('m')
            ->innerJoin('m.semestres','s')
            ->where('s.id = :semestre')
            ->setParameter('semestre', $semestre->getId())
            ->getQuery()
            ->getResult();
    }

    public function findMatieres(){
        return $this->createQueryBuilder('m')
            ->innerJoin('m.matieres', 'matiere')
            ->getQuery()
            ->getResult();
    }
}
