<?php

namespace UpjvBundle\Repository;

/**
 * PoleDeCompetenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoleDeCompetenceRepository extends \Doctrine\ORM\EntityRepository
{
}
