<?php

namespace UpjvBundle\Repository;

/**
 * PoleDeCompetenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoleDeCompetenceRepository extends \Doctrine\ORM\EntityRepository
{
    public function resetAllPole()
    {
        $rawSql = "DELETE FROM pole_de_competence";
        $stmt = $this->getEntityManager()->getConnection()->prepare($rawSql);
        $stmt->execute();
    }
}
