<?php

namespace UpjvBundle\Repository;
use UpjvBundle\Entity\PoleDeCompetence;
use UpjvBundle\Entity\Utilisateur;

/**
 * ParcoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoleDeCompetenceParcoursRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNbrMatiereOptionnelMustHaveUserByPole(Utilisateur $user,PoleDeCompetence $poleDeCompetence){
        $result = $this->createQueryBuilder('p')
            ->select('p.nbrMatiereOptionnelle')
            ->join('p.parcours','parcours')
            ->join('parcours.matieres','matieres')
            ->join('p.poleDeCompetence','poleDeCompetence')
            ->join('parcours.utilisateur','utilisateur')
            ->where('utilisateur = :utilisateur')
            ->setParameter('utilisateur',$user)
            ->andWhere('poleDeCompetence = :poleDeCompetence')
            ->setParameter('poleDeCompetence',$poleDeCompetence)
            ->distinct()
            ->getQuery()
            ->getResult();

        return $result[0]['nbrMatiereOptionnelle'];
    }

}